version: "3"
services:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - data:/data/db
    image: mongo:4.4
    networks:
      - mygoals
  backend:
    networks:
      - mygoals
    ports:
      - 80:80
    volumes:
      - logs:/logs
      - node_modules:/node_modules
    image: ribanec/goals-backend
  frontend:
    networks:
      - mygoals
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/src
      - node_modules:/node_modules
    image: ribanec/goals-frontend
networks:
  mygoals:
volumes:
  data:
  logs:
  node_modules:
